// Code generated by ent, DO NOT EDIT.

package post

import (
	"api/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldID, id))
}

// PostTitle applies equality check predicate on the "post_title" field. It's identical to PostTitleEQ.
func PostTitle(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldPostTitle, v))
}

// PostContent applies equality check predicate on the "post_content" field. It's identical to PostContentEQ.
func PostContent(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldPostContent, v))
}

// PostTitleEQ applies the EQ predicate on the "post_title" field.
func PostTitleEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldPostTitle, v))
}

// PostTitleNEQ applies the NEQ predicate on the "post_title" field.
func PostTitleNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldPostTitle, v))
}

// PostTitleIn applies the In predicate on the "post_title" field.
func PostTitleIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldPostTitle, vs...))
}

// PostTitleNotIn applies the NotIn predicate on the "post_title" field.
func PostTitleNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldPostTitle, vs...))
}

// PostTitleGT applies the GT predicate on the "post_title" field.
func PostTitleGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldPostTitle, v))
}

// PostTitleGTE applies the GTE predicate on the "post_title" field.
func PostTitleGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldPostTitle, v))
}

// PostTitleLT applies the LT predicate on the "post_title" field.
func PostTitleLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldPostTitle, v))
}

// PostTitleLTE applies the LTE predicate on the "post_title" field.
func PostTitleLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldPostTitle, v))
}

// PostTitleContains applies the Contains predicate on the "post_title" field.
func PostTitleContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldPostTitle, v))
}

// PostTitleHasPrefix applies the HasPrefix predicate on the "post_title" field.
func PostTitleHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldPostTitle, v))
}

// PostTitleHasSuffix applies the HasSuffix predicate on the "post_title" field.
func PostTitleHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldPostTitle, v))
}

// PostTitleEqualFold applies the EqualFold predicate on the "post_title" field.
func PostTitleEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldPostTitle, v))
}

// PostTitleContainsFold applies the ContainsFold predicate on the "post_title" field.
func PostTitleContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldPostTitle, v))
}

// PostContentEQ applies the EQ predicate on the "post_content" field.
func PostContentEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldEQ(FieldPostContent, v))
}

// PostContentNEQ applies the NEQ predicate on the "post_content" field.
func PostContentNEQ(v string) predicate.Post {
	return predicate.Post(sql.FieldNEQ(FieldPostContent, v))
}

// PostContentIn applies the In predicate on the "post_content" field.
func PostContentIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldIn(FieldPostContent, vs...))
}

// PostContentNotIn applies the NotIn predicate on the "post_content" field.
func PostContentNotIn(vs ...string) predicate.Post {
	return predicate.Post(sql.FieldNotIn(FieldPostContent, vs...))
}

// PostContentGT applies the GT predicate on the "post_content" field.
func PostContentGT(v string) predicate.Post {
	return predicate.Post(sql.FieldGT(FieldPostContent, v))
}

// PostContentGTE applies the GTE predicate on the "post_content" field.
func PostContentGTE(v string) predicate.Post {
	return predicate.Post(sql.FieldGTE(FieldPostContent, v))
}

// PostContentLT applies the LT predicate on the "post_content" field.
func PostContentLT(v string) predicate.Post {
	return predicate.Post(sql.FieldLT(FieldPostContent, v))
}

// PostContentLTE applies the LTE predicate on the "post_content" field.
func PostContentLTE(v string) predicate.Post {
	return predicate.Post(sql.FieldLTE(FieldPostContent, v))
}

// PostContentContains applies the Contains predicate on the "post_content" field.
func PostContentContains(v string) predicate.Post {
	return predicate.Post(sql.FieldContains(FieldPostContent, v))
}

// PostContentHasPrefix applies the HasPrefix predicate on the "post_content" field.
func PostContentHasPrefix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasPrefix(FieldPostContent, v))
}

// PostContentHasSuffix applies the HasSuffix predicate on the "post_content" field.
func PostContentHasSuffix(v string) predicate.Post {
	return predicate.Post(sql.FieldHasSuffix(FieldPostContent, v))
}

// PostContentIsNil applies the IsNil predicate on the "post_content" field.
func PostContentIsNil() predicate.Post {
	return predicate.Post(sql.FieldIsNull(FieldPostContent))
}

// PostContentNotNil applies the NotNil predicate on the "post_content" field.
func PostContentNotNil() predicate.Post {
	return predicate.Post(sql.FieldNotNull(FieldPostContent))
}

// PostContentEqualFold applies the EqualFold predicate on the "post_content" field.
func PostContentEqualFold(v string) predicate.Post {
	return predicate.Post(sql.FieldEqualFold(FieldPostContent, v))
}

// PostContentContainsFold applies the ContainsFold predicate on the "post_content" field.
func PostContentContainsFold(v string) predicate.Post {
	return predicate.Post(sql.FieldContainsFold(FieldPostContent, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Post) predicate.Post {
	return predicate.Post(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Post) predicate.Post {
	return predicate.Post(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Post) predicate.Post {
	return predicate.Post(sql.NotPredicates(p))
}
