// Code generated by ent, DO NOT EDIT.

package user

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAd holds the string denoting the ad field in the database.
	FieldAd = "ad"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// EdgeURL holds the string denoting the url edge name in mutations.
	EdgeURL = "url"
	// EdgeLog holds the string denoting the log edge name in mutations.
	EdgeLog = "log"
	// Table holds the table name of the user in the database.
	Table = "users"
	// URLTable is the table that holds the url relation/edge.
	URLTable = "urls"
	// URLInverseTable is the table name for the Url entity.
	// It exists in this package in order to avoid circular dependency with the "url" package.
	URLInverseTable = "urls"
	// URLColumn is the table column denoting the url relation/edge.
	URLColumn = "user_url"
	// LogTable is the table that holds the log relation/edge.
	LogTable = "logs"
	// LogInverseTable is the table name for the Logs entity.
	// It exists in this package in order to avoid circular dependency with the "logs" package.
	LogInverseTable = "logs"
	// LogColumn is the table column denoting the log relation/edge.
	LogColumn = "user_log"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldAd,
	FieldEmail,
	FieldPassword,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// AdValidator is a validator for the "ad" field. It is called by the builders before save.
	AdValidator func(string) error
)

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAd orders the results by the ad field.
func ByAd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAd, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByURLCount orders the results by url count.
func ByURLCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newURLStep(), opts...)
	}
}

// ByURL orders the results by url terms.
func ByURL(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newURLStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByLogCount orders the results by log count.
func ByLogCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLogStep(), opts...)
	}
}

// ByLog orders the results by log terms.
func ByLog(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLogStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newURLStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(URLInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, URLTable, URLColumn),
	)
}
func newLogStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LogInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LogTable, LogColumn),
	)
}
