services:
  - type: web
    name: api-service
    env: host        # 'go' yerine 'host' yapıyoruz
    plan: free
    # Go yüklü mü diye kontrol edip derleme yapıyoruz
    buildCommand: go build -o api-app ./api
    startCommand: ./api-app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urlshorter
          property: connectionString
      - key: GO_VERSION
        value: 1.22.0

  - type: web
    name: site-service
    env: host        # 'go' yerine 'host' yapıyoruz
    plan: free
    buildCommand: go build -o site-app ./client
    startCommand: ./site-app
    envVars:
      - key: GO_VERSION
        value: 1.22.0