services:
  - type: web
    name: api-service
    env: go
    rootDir: apps/2
    buildCommand: go build -o main
    startCommand: ./main
    goVersion: 1.22
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: urlshorter
          property: connectionString

  - type: web
    name: site-service
    env: go
    rootDir: apps/client_
    buildCommand: go build -o site
    startCommand: ./site
    goVersion: 1.22