services:
  - type: web
    name: api-service
    runtime: go
    plan: free
    buildCommand: |
      mkdir -p bin
      go build -o bin/api-service ./api
      cp -r ./api/conf bin/conf || true
    startCommand: cd bin && ./api-service
   

  - type: web
    name: site-service
    runtime: go
    plan: free
    buildCommand: |
      mkdir -p bin && go build -o bin/site-service ./client_ && cp -r ./client_/conf ./bin/ || true && cp -r ./client_/views ./bin/
    startCommand: cd bin && ./site-service
    envVars:
      - key: GO_VERSION
        value: 1.22.0
      - key: API_URL
        fromService:
          name: api-service
          type: web
          property: url