// Code generated by ent, DO NOT EDIT.

package url

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the url type in the database.
	Label = "url"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldShortCode holds the string denoting the short_code field in the database.
	FieldShortCode = "short_code"
	// FieldLongURL holds the string denoting the long_url field in the database.
	FieldLongURL = "long_url"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldAlias holds the string denoting the alias field in the database.
	FieldAlias = "alias"
	// FieldIsEncrypted holds the string denoting the is_encrypted field in the database.
	FieldIsEncrypted = "is_encrypted"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldExpirationDate holds the string denoting the expiration_date field in the database.
	FieldExpirationDate = "expiration_date"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeLogURL holds the string denoting the log_url edge name in mutations.
	EdgeLogURL = "log_url"
	// Table holds the table name of the url in the database.
	Table = "urls"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "urls"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_url"
	// LogURLTable is the table that holds the log_url relation/edge.
	LogURLTable = "logs"
	// LogURLInverseTable is the table name for the Logs entity.
	// It exists in this package in order to avoid circular dependency with the "logs" package.
	LogURLInverseTable = "logs"
	// LogURLColumn is the table column denoting the log_url relation/edge.
	LogURLColumn = "url_log_url"
)

// Columns holds all SQL columns for url fields.
var Columns = []string{
	FieldID,
	FieldShortCode,
	FieldLongURL,
	FieldCreatedAt,
	FieldAlias,
	FieldIsEncrypted,
	FieldPassword,
	FieldExpirationDate,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "urls"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"user_url",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

var (
	// ShortCodeValidator is a validator for the "short_code" field. It is called by the builders before save.
	ShortCodeValidator func(string) error
	// LongURLValidator is a validator for the "long_url" field. It is called by the builders before save.
	LongURLValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultIsEncrypted holds the default value on creation for the "is_encrypted" field.
	DefaultIsEncrypted bool
)

// OrderOption defines the ordering options for the Url queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByShortCode orders the results by the short_code field.
func ByShortCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldShortCode, opts...).ToFunc()
}

// ByLongURL orders the results by the long_url field.
func ByLongURL(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLongURL, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByAlias orders the results by the alias field.
func ByAlias(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAlias, opts...).ToFunc()
}

// ByIsEncrypted orders the results by the is_encrypted field.
func ByIsEncrypted(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsEncrypted, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByExpirationDate orders the results by the expiration_date field.
func ByExpirationDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpirationDate, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}

// ByLogURLCount orders the results by log_url count.
func ByLogURLCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newLogURLStep(), opts...)
	}
}

// ByLogURL orders the results by log_url terms.
func ByLogURL(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLogURLStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
func newLogURLStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LogURLInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, LogURLTable, LogURLColumn),
	)
}
