// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/logs"
	"api/ent/url"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Logs is the model entity for the Logs schema.
type Logs struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Device holds the value of the "device" field.
	Device string `json:"device,omitempty"`
	// IP holds the value of the "ip" field.
	IP string `json:"ip,omitempty"`
	// Referer holds the value of the "referer" field.
	Referer string `json:"referer,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the LogsQuery when eager-loading is set.
	Edges        LogsEdges `json:"edges"`
	url_log_url  *int
	selectValues sql.SelectValues
}

// LogsEdges holds the relations/edges for other nodes in the graph.
type LogsEdges struct {
	// Log holds the value of the log edge.
	Log *Url `json:"log,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// LogOrErr returns the Log value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e LogsEdges) LogOrErr() (*Url, error) {
	if e.Log != nil {
		return e.Log, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: url.Label}
	}
	return nil, &NotLoadedError{edge: "log"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Logs) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case logs.FieldID:
			values[i] = new(sql.NullInt64)
		case logs.FieldDevice, logs.FieldIP, logs.FieldReferer:
			values[i] = new(sql.NullString)
		case logs.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case logs.ForeignKeys[0]: // url_log_url
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Logs fields.
func (_m *Logs) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case logs.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case logs.FieldDevice:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field device", values[i])
			} else if value.Valid {
				_m.Device = value.String
			}
		case logs.FieldIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ip", values[i])
			} else if value.Valid {
				_m.IP = value.String
			}
		case logs.FieldReferer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field referer", values[i])
			} else if value.Valid {
				_m.Referer = value.String
			}
		case logs.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case logs.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field url_log_url", value)
			} else if value.Valid {
				_m.url_log_url = new(int)
				*_m.url_log_url = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Logs.
// This includes values selected through modifiers, order, etc.
func (_m *Logs) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryLog queries the "log" edge of the Logs entity.
func (_m *Logs) QueryLog() *URLQuery {
	return NewLogsClient(_m.config).QueryLog(_m)
}

// Update returns a builder for updating this Logs.
// Note that you need to call Logs.Unwrap() before calling this method if this Logs
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Logs) Update() *LogsUpdateOne {
	return NewLogsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Logs entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Logs) Unwrap() *Logs {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Logs is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Logs) String() string {
	var builder strings.Builder
	builder.WriteString("Logs(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("device=")
	builder.WriteString(_m.Device)
	builder.WriteString(", ")
	builder.WriteString("ip=")
	builder.WriteString(_m.IP)
	builder.WriteString(", ")
	builder.WriteString("referer=")
	builder.WriteString(_m.Referer)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// LogsSlice is a parsable slice of Logs.
type LogsSlice []*Logs
