// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/post"
	"api/ent/schema"
	"api/ent/url"
	"api/ent/user"
	"time"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	postFields := schema.Post{}.Fields()
	_ = postFields
	// postDescPostTitle is the schema descriptor for post_title field.
	postDescPostTitle := postFields[0].Descriptor()
	// post.PostTitleValidator is a validator for the "post_title" field. It is called by the builders before save.
	post.PostTitleValidator = postDescPostTitle.Validators[0].(func(string) error)
	urlFields := schema.Url{}.Fields()
	_ = urlFields
	// urlDescShortCode is the schema descriptor for short_code field.
	urlDescShortCode := urlFields[0].Descriptor()
	// url.ShortCodeValidator is a validator for the "short_code" field. It is called by the builders before save.
	url.ShortCodeValidator = func() func(string) error {
		validators := urlDescShortCode.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(short_code string) error {
			for _, fn := range fns {
				if err := fn(short_code); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// urlDescLongURL is the schema descriptor for long_url field.
	urlDescLongURL := urlFields[1].Descriptor()
	// url.LongURLValidator is a validator for the "long_url" field. It is called by the builders before save.
	url.LongURLValidator = urlDescLongURL.Validators[0].(func(string) error)
	// urlDescCreatedAt is the schema descriptor for created_at field.
	urlDescCreatedAt := urlFields[2].Descriptor()
	// url.DefaultCreatedAt holds the default value on creation for the created_at field.
	url.DefaultCreatedAt = urlDescCreatedAt.Default.(func() time.Time)
	// urlDescIsEncrypted is the schema descriptor for is_encrypted field.
	urlDescIsEncrypted := urlFields[4].Descriptor()
	// url.DefaultIsEncrypted holds the default value on creation for the is_encrypted field.
	url.DefaultIsEncrypted = urlDescIsEncrypted.Default.(bool)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescAd is the schema descriptor for ad field.
	userDescAd := userFields[0].Descriptor()
	// user.AdValidator is a validator for the "ad" field. It is called by the builders before save.
	user.AdValidator = userDescAd.Validators[0].(func(string) error)
}
