// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/logs"
	"api/ent/predicate"
	"api/ent/url"
	"api/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// URLUpdate is the builder for updating Url entities.
type URLUpdate struct {
	config
	hooks     []Hook
	mutation  *URLMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the URLUpdate builder.
func (_u *URLUpdate) Where(ps ...predicate.Url) *URLUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetShortCode sets the "short_code" field.
func (_u *URLUpdate) SetShortCode(v string) *URLUpdate {
	_u.mutation.SetShortCode(v)
	return _u
}

// SetNillableShortCode sets the "short_code" field if the given value is not nil.
func (_u *URLUpdate) SetNillableShortCode(v *string) *URLUpdate {
	if v != nil {
		_u.SetShortCode(*v)
	}
	return _u
}

// SetLongURL sets the "long_url" field.
func (_u *URLUpdate) SetLongURL(v string) *URLUpdate {
	_u.mutation.SetLongURL(v)
	return _u
}

// SetNillableLongURL sets the "long_url" field if the given value is not nil.
func (_u *URLUpdate) SetNillableLongURL(v *string) *URLUpdate {
	if v != nil {
		_u.SetLongURL(*v)
	}
	return _u
}

// SetAlias sets the "alias" field.
func (_u *URLUpdate) SetAlias(v string) *URLUpdate {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *URLUpdate) SetNillableAlias(v *string) *URLUpdate {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// ClearAlias clears the value of the "alias" field.
func (_u *URLUpdate) ClearAlias() *URLUpdate {
	_u.mutation.ClearAlias()
	return _u
}

// SetIsEncrypted sets the "is_encrypted" field.
func (_u *URLUpdate) SetIsEncrypted(v bool) *URLUpdate {
	_u.mutation.SetIsEncrypted(v)
	return _u
}

// SetNillableIsEncrypted sets the "is_encrypted" field if the given value is not nil.
func (_u *URLUpdate) SetNillableIsEncrypted(v *bool) *URLUpdate {
	if v != nil {
		_u.SetIsEncrypted(*v)
	}
	return _u
}

// ClearIsEncrypted clears the value of the "is_encrypted" field.
func (_u *URLUpdate) ClearIsEncrypted() *URLUpdate {
	_u.mutation.ClearIsEncrypted()
	return _u
}

// SetPassword sets the "password" field.
func (_u *URLUpdate) SetPassword(v string) *URLUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *URLUpdate) SetNillablePassword(v *string) *URLUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *URLUpdate) ClearPassword() *URLUpdate {
	_u.mutation.ClearPassword()
	return _u
}

// SetExpirationDate sets the "expiration_date" field.
func (_u *URLUpdate) SetExpirationDate(v time.Time) *URLUpdate {
	_u.mutation.SetExpirationDate(v)
	return _u
}

// SetNillableExpirationDate sets the "expiration_date" field if the given value is not nil.
func (_u *URLUpdate) SetNillableExpirationDate(v *time.Time) *URLUpdate {
	if v != nil {
		_u.SetExpirationDate(*v)
	}
	return _u
}

// ClearExpirationDate clears the value of the "expiration_date" field.
func (_u *URLUpdate) ClearExpirationDate() *URLUpdate {
	_u.mutation.ClearExpirationDate()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *URLUpdate) SetUserID(id int) *URLUpdate {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *URLUpdate) SetUser(v *User) *URLUpdate {
	return _u.SetUserID(v.ID)
}

// AddLogURLIDs adds the "log_url" edge to the Logs entity by IDs.
func (_u *URLUpdate) AddLogURLIDs(ids ...int) *URLUpdate {
	_u.mutation.AddLogURLIDs(ids...)
	return _u
}

// AddLogURL adds the "log_url" edges to the Logs entity.
func (_u *URLUpdate) AddLogURL(v ...*Logs) *URLUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLogURLIDs(ids...)
}

// Mutation returns the URLMutation object of the builder.
func (_u *URLUpdate) Mutation() *URLMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *URLUpdate) ClearUser() *URLUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearLogURL clears all "log_url" edges to the Logs entity.
func (_u *URLUpdate) ClearLogURL() *URLUpdate {
	_u.mutation.ClearLogURL()
	return _u
}

// RemoveLogURLIDs removes the "log_url" edge to Logs entities by IDs.
func (_u *URLUpdate) RemoveLogURLIDs(ids ...int) *URLUpdate {
	_u.mutation.RemoveLogURLIDs(ids...)
	return _u
}

// RemoveLogURL removes "log_url" edges to Logs entities.
func (_u *URLUpdate) RemoveLogURL(v ...*Logs) *URLUpdate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLogURLIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *URLUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *URLUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *URLUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *URLUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *URLUpdate) check() error {
	if v, ok := _u.mutation.ShortCode(); ok {
		if err := url.ShortCodeValidator(v); err != nil {
			return &ValidationError{Name: "short_code", err: fmt.Errorf(`ent: validator failed for field "Url.short_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LongURL(); ok {
		if err := url.LongURLValidator(v); err != nil {
			return &ValidationError{Name: "long_url", err: fmt.Errorf(`ent: validator failed for field "Url.long_url": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Url.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *URLUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *URLUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *URLUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(url.Table, url.Columns, sqlgraph.NewFieldSpec(url.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ShortCode(); ok {
		_spec.SetField(url.FieldShortCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.LongURL(); ok {
		_spec.SetField(url.FieldLongURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(url.FieldAlias, field.TypeString, value)
	}
	if _u.mutation.AliasCleared() {
		_spec.ClearField(url.FieldAlias, field.TypeString)
	}
	if value, ok := _u.mutation.IsEncrypted(); ok {
		_spec.SetField(url.FieldIsEncrypted, field.TypeBool, value)
	}
	if _u.mutation.IsEncryptedCleared() {
		_spec.ClearField(url.FieldIsEncrypted, field.TypeBool)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(url.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(url.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.ExpirationDate(); ok {
		_spec.SetField(url.FieldExpirationDate, field.TypeTime, value)
	}
	if _u.mutation.ExpirationDateCleared() {
		_spec.ClearField(url.FieldExpirationDate, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   url.UserTable,
			Columns: []string{url.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   url.UserTable,
			Columns: []string{url.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LogURLCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   url.LogURLTable,
			Columns: []string{url.LogURLColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(logs.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLogURLIDs(); len(nodes) > 0 && !_u.mutation.LogURLCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   url.LogURLTable,
			Columns: []string{url.LogURLColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(logs.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LogURLIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   url.LogURLTable,
			Columns: []string{url.LogURLColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(logs.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{url.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// URLUpdateOne is the builder for updating a single Url entity.
type URLUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *URLMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetShortCode sets the "short_code" field.
func (_u *URLUpdateOne) SetShortCode(v string) *URLUpdateOne {
	_u.mutation.SetShortCode(v)
	return _u
}

// SetNillableShortCode sets the "short_code" field if the given value is not nil.
func (_u *URLUpdateOne) SetNillableShortCode(v *string) *URLUpdateOne {
	if v != nil {
		_u.SetShortCode(*v)
	}
	return _u
}

// SetLongURL sets the "long_url" field.
func (_u *URLUpdateOne) SetLongURL(v string) *URLUpdateOne {
	_u.mutation.SetLongURL(v)
	return _u
}

// SetNillableLongURL sets the "long_url" field if the given value is not nil.
func (_u *URLUpdateOne) SetNillableLongURL(v *string) *URLUpdateOne {
	if v != nil {
		_u.SetLongURL(*v)
	}
	return _u
}

// SetAlias sets the "alias" field.
func (_u *URLUpdateOne) SetAlias(v string) *URLUpdateOne {
	_u.mutation.SetAlias(v)
	return _u
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_u *URLUpdateOne) SetNillableAlias(v *string) *URLUpdateOne {
	if v != nil {
		_u.SetAlias(*v)
	}
	return _u
}

// ClearAlias clears the value of the "alias" field.
func (_u *URLUpdateOne) ClearAlias() *URLUpdateOne {
	_u.mutation.ClearAlias()
	return _u
}

// SetIsEncrypted sets the "is_encrypted" field.
func (_u *URLUpdateOne) SetIsEncrypted(v bool) *URLUpdateOne {
	_u.mutation.SetIsEncrypted(v)
	return _u
}

// SetNillableIsEncrypted sets the "is_encrypted" field if the given value is not nil.
func (_u *URLUpdateOne) SetNillableIsEncrypted(v *bool) *URLUpdateOne {
	if v != nil {
		_u.SetIsEncrypted(*v)
	}
	return _u
}

// ClearIsEncrypted clears the value of the "is_encrypted" field.
func (_u *URLUpdateOne) ClearIsEncrypted() *URLUpdateOne {
	_u.mutation.ClearIsEncrypted()
	return _u
}

// SetPassword sets the "password" field.
func (_u *URLUpdateOne) SetPassword(v string) *URLUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *URLUpdateOne) SetNillablePassword(v *string) *URLUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *URLUpdateOne) ClearPassword() *URLUpdateOne {
	_u.mutation.ClearPassword()
	return _u
}

// SetExpirationDate sets the "expiration_date" field.
func (_u *URLUpdateOne) SetExpirationDate(v time.Time) *URLUpdateOne {
	_u.mutation.SetExpirationDate(v)
	return _u
}

// SetNillableExpirationDate sets the "expiration_date" field if the given value is not nil.
func (_u *URLUpdateOne) SetNillableExpirationDate(v *time.Time) *URLUpdateOne {
	if v != nil {
		_u.SetExpirationDate(*v)
	}
	return _u
}

// ClearExpirationDate clears the value of the "expiration_date" field.
func (_u *URLUpdateOne) ClearExpirationDate() *URLUpdateOne {
	_u.mutation.ClearExpirationDate()
	return _u
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_u *URLUpdateOne) SetUserID(id int) *URLUpdateOne {
	_u.mutation.SetUserID(id)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *URLUpdateOne) SetUser(v *User) *URLUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddLogURLIDs adds the "log_url" edge to the Logs entity by IDs.
func (_u *URLUpdateOne) AddLogURLIDs(ids ...int) *URLUpdateOne {
	_u.mutation.AddLogURLIDs(ids...)
	return _u
}

// AddLogURL adds the "log_url" edges to the Logs entity.
func (_u *URLUpdateOne) AddLogURL(v ...*Logs) *URLUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddLogURLIDs(ids...)
}

// Mutation returns the URLMutation object of the builder.
func (_u *URLUpdateOne) Mutation() *URLMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *URLUpdateOne) ClearUser() *URLUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearLogURL clears all "log_url" edges to the Logs entity.
func (_u *URLUpdateOne) ClearLogURL() *URLUpdateOne {
	_u.mutation.ClearLogURL()
	return _u
}

// RemoveLogURLIDs removes the "log_url" edge to Logs entities by IDs.
func (_u *URLUpdateOne) RemoveLogURLIDs(ids ...int) *URLUpdateOne {
	_u.mutation.RemoveLogURLIDs(ids...)
	return _u
}

// RemoveLogURL removes "log_url" edges to Logs entities.
func (_u *URLUpdateOne) RemoveLogURL(v ...*Logs) *URLUpdateOne {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveLogURLIDs(ids...)
}

// Where appends a list predicates to the URLUpdate builder.
func (_u *URLUpdateOne) Where(ps ...predicate.Url) *URLUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *URLUpdateOne) Select(field string, fields ...string) *URLUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Url entity.
func (_u *URLUpdateOne) Save(ctx context.Context) (*Url, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *URLUpdateOne) SaveX(ctx context.Context) *Url {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *URLUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *URLUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *URLUpdateOne) check() error {
	if v, ok := _u.mutation.ShortCode(); ok {
		if err := url.ShortCodeValidator(v); err != nil {
			return &ValidationError{Name: "short_code", err: fmt.Errorf(`ent: validator failed for field "Url.short_code": %w`, err)}
		}
	}
	if v, ok := _u.mutation.LongURL(); ok {
		if err := url.LongURLValidator(v); err != nil {
			return &ValidationError{Name: "long_url", err: fmt.Errorf(`ent: validator failed for field "Url.long_url": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Url.user"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *URLUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *URLUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *URLUpdateOne) sqlSave(ctx context.Context) (_node *Url, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(url.Table, url.Columns, sqlgraph.NewFieldSpec(url.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Url.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, url.FieldID)
		for _, f := range fields {
			if !url.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != url.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.ShortCode(); ok {
		_spec.SetField(url.FieldShortCode, field.TypeString, value)
	}
	if value, ok := _u.mutation.LongURL(); ok {
		_spec.SetField(url.FieldLongURL, field.TypeString, value)
	}
	if value, ok := _u.mutation.Alias(); ok {
		_spec.SetField(url.FieldAlias, field.TypeString, value)
	}
	if _u.mutation.AliasCleared() {
		_spec.ClearField(url.FieldAlias, field.TypeString)
	}
	if value, ok := _u.mutation.IsEncrypted(); ok {
		_spec.SetField(url.FieldIsEncrypted, field.TypeBool, value)
	}
	if _u.mutation.IsEncryptedCleared() {
		_spec.ClearField(url.FieldIsEncrypted, field.TypeBool)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(url.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(url.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.ExpirationDate(); ok {
		_spec.SetField(url.FieldExpirationDate, field.TypeTime, value)
	}
	if _u.mutation.ExpirationDateCleared() {
		_spec.ClearField(url.FieldExpirationDate, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   url.UserTable,
			Columns: []string{url.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   url.UserTable,
			Columns: []string{url.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.LogURLCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   url.LogURLTable,
			Columns: []string{url.LogURLColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(logs.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedLogURLIDs(); len(nodes) > 0 && !_u.mutation.LogURLCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   url.LogURLTable,
			Columns: []string{url.LogURLColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(logs.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LogURLIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   url.LogURLTable,
			Columns: []string{url.LogURLColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(logs.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Url{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{url.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
