// Code generated by ent, DO NOT EDIT.

package ent

import (
	"api/ent/logs"
	"api/ent/url"
	"api/ent/user"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// URLCreate is the builder for creating a Url entity.
type URLCreate struct {
	config
	mutation *URLMutation
	hooks    []Hook
}

// SetShortCode sets the "short_code" field.
func (_c *URLCreate) SetShortCode(v string) *URLCreate {
	_c.mutation.SetShortCode(v)
	return _c
}

// SetLongURL sets the "long_url" field.
func (_c *URLCreate) SetLongURL(v string) *URLCreate {
	_c.mutation.SetLongURL(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *URLCreate) SetCreatedAt(v time.Time) *URLCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *URLCreate) SetNillableCreatedAt(v *time.Time) *URLCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetAlias sets the "alias" field.
func (_c *URLCreate) SetAlias(v string) *URLCreate {
	_c.mutation.SetAlias(v)
	return _c
}

// SetNillableAlias sets the "alias" field if the given value is not nil.
func (_c *URLCreate) SetNillableAlias(v *string) *URLCreate {
	if v != nil {
		_c.SetAlias(*v)
	}
	return _c
}

// SetIsEncrypted sets the "is_encrypted" field.
func (_c *URLCreate) SetIsEncrypted(v bool) *URLCreate {
	_c.mutation.SetIsEncrypted(v)
	return _c
}

// SetNillableIsEncrypted sets the "is_encrypted" field if the given value is not nil.
func (_c *URLCreate) SetNillableIsEncrypted(v *bool) *URLCreate {
	if v != nil {
		_c.SetIsEncrypted(*v)
	}
	return _c
}

// SetPassword sets the "password" field.
func (_c *URLCreate) SetPassword(v string) *URLCreate {
	_c.mutation.SetPassword(v)
	return _c
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_c *URLCreate) SetNillablePassword(v *string) *URLCreate {
	if v != nil {
		_c.SetPassword(*v)
	}
	return _c
}

// SetExpirationDate sets the "expiration_date" field.
func (_c *URLCreate) SetExpirationDate(v time.Time) *URLCreate {
	_c.mutation.SetExpirationDate(v)
	return _c
}

// SetNillableExpirationDate sets the "expiration_date" field if the given value is not nil.
func (_c *URLCreate) SetNillableExpirationDate(v *time.Time) *URLCreate {
	if v != nil {
		_c.SetExpirationDate(*v)
	}
	return _c
}

// SetUserID sets the "user" edge to the User entity by ID.
func (_c *URLCreate) SetUserID(id int) *URLCreate {
	_c.mutation.SetUserID(id)
	return _c
}

// SetNillableUserID sets the "user" edge to the User entity by ID if the given value is not nil.
func (_c *URLCreate) SetNillableUserID(id *int) *URLCreate {
	if id != nil {
		_c = _c.SetUserID(*id)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *URLCreate) SetUser(v *User) *URLCreate {
	return _c.SetUserID(v.ID)
}

// AddLogURLIDs adds the "log_url" edge to the Logs entity by IDs.
func (_c *URLCreate) AddLogURLIDs(ids ...int) *URLCreate {
	_c.mutation.AddLogURLIDs(ids...)
	return _c
}

// AddLogURL adds the "log_url" edges to the Logs entity.
func (_c *URLCreate) AddLogURL(v ...*Logs) *URLCreate {
	ids := make([]int, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLogURLIDs(ids...)
}

// Mutation returns the URLMutation object of the builder.
func (_c *URLCreate) Mutation() *URLMutation {
	return _c.mutation
}

// Save creates the Url in the database.
func (_c *URLCreate) Save(ctx context.Context) (*Url, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *URLCreate) SaveX(ctx context.Context) *Url {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *URLCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *URLCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *URLCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := url.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.IsEncrypted(); !ok {
		v := url.DefaultIsEncrypted
		_c.mutation.SetIsEncrypted(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *URLCreate) check() error {
	if _, ok := _c.mutation.ShortCode(); !ok {
		return &ValidationError{Name: "short_code", err: errors.New(`ent: missing required field "Url.short_code"`)}
	}
	if v, ok := _c.mutation.ShortCode(); ok {
		if err := url.ShortCodeValidator(v); err != nil {
			return &ValidationError{Name: "short_code", err: fmt.Errorf(`ent: validator failed for field "Url.short_code": %w`, err)}
		}
	}
	if _, ok := _c.mutation.LongURL(); !ok {
		return &ValidationError{Name: "long_url", err: errors.New(`ent: missing required field "Url.long_url"`)}
	}
	if v, ok := _c.mutation.LongURL(); ok {
		if err := url.LongURLValidator(v); err != nil {
			return &ValidationError{Name: "long_url", err: fmt.Errorf(`ent: validator failed for field "Url.long_url": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Url.created_at"`)}
	}
	return nil
}

func (_c *URLCreate) sqlSave(ctx context.Context) (*Url, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *URLCreate) createSpec() (*Url, *sqlgraph.CreateSpec) {
	var (
		_node = &Url{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(url.Table, sqlgraph.NewFieldSpec(url.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.ShortCode(); ok {
		_spec.SetField(url.FieldShortCode, field.TypeString, value)
		_node.ShortCode = value
	}
	if value, ok := _c.mutation.LongURL(); ok {
		_spec.SetField(url.FieldLongURL, field.TypeString, value)
		_node.LongURL = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(url.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.Alias(); ok {
		_spec.SetField(url.FieldAlias, field.TypeString, value)
		_node.Alias = value
	}
	if value, ok := _c.mutation.IsEncrypted(); ok {
		_spec.SetField(url.FieldIsEncrypted, field.TypeBool, value)
		_node.IsEncrypted = value
	}
	if value, ok := _c.mutation.Password(); ok {
		_spec.SetField(url.FieldPassword, field.TypeString, value)
		_node.Password = value
	}
	if value, ok := _c.mutation.ExpirationDate(); ok {
		_spec.SetField(url.FieldExpirationDate, field.TypeTime, value)
		_node.ExpirationDate = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   url.UserTable,
			Columns: []string{url.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.user_url = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LogURLIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   url.LogURLTable,
			Columns: []string{url.LogURLColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(logs.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// URLCreateBulk is the builder for creating many Url entities in bulk.
type URLCreateBulk struct {
	config
	err      error
	builders []*URLCreate
}

// Save creates the Url entities in the database.
func (_c *URLCreateBulk) Save(ctx context.Context) ([]*Url, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Url, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*URLMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *URLCreateBulk) SaveX(ctx context.Context) []*Url {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *URLCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *URLCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
