// Code generated by ent, DO NOT EDIT.

package ent

import (
	"2/ent/logs"
	"2/ent/predicate"
	"2/ent/url"
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LogsUpdate is the builder for updating Logs entities.
type LogsUpdate struct {
	config
	hooks     []Hook
	mutation  *LogsMutation
	modifiers []func(*sql.UpdateBuilder)
}

// Where appends a list predicates to the LogsUpdate builder.
func (_u *LogsUpdate) Where(ps ...predicate.Logs) *LogsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDevice sets the "device" field.
func (_u *LogsUpdate) SetDevice(v string) *LogsUpdate {
	_u.mutation.SetDevice(v)
	return _u
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_u *LogsUpdate) SetNillableDevice(v *string) *LogsUpdate {
	if v != nil {
		_u.SetDevice(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *LogsUpdate) SetIP(v string) *LogsUpdate {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *LogsUpdate) SetNillableIP(v *string) *LogsUpdate {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetReferer sets the "referer" field.
func (_u *LogsUpdate) SetReferer(v string) *LogsUpdate {
	_u.mutation.SetReferer(v)
	return _u
}

// SetNillableReferer sets the "referer" field if the given value is not nil.
func (_u *LogsUpdate) SetNillableReferer(v *string) *LogsUpdate {
	if v != nil {
		_u.SetReferer(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LogsUpdate) SetCreatedAt(v time.Time) *LogsUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LogsUpdate) SetNillableCreatedAt(v *time.Time) *LogsUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetLogID sets the "log" edge to the Url entity by ID.
func (_u *LogsUpdate) SetLogID(id int) *LogsUpdate {
	_u.mutation.SetLogID(id)
	return _u
}

// SetLog sets the "log" edge to the Url entity.
func (_u *LogsUpdate) SetLog(v *Url) *LogsUpdate {
	return _u.SetLogID(v.ID)
}

// Mutation returns the LogsMutation object of the builder.
func (_u *LogsUpdate) Mutation() *LogsMutation {
	return _u.mutation
}

// ClearLog clears the "log" edge to the Url entity.
func (_u *LogsUpdate) ClearLog() *LogsUpdate {
	_u.mutation.ClearLog()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *LogsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LogsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *LogsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LogsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LogsUpdate) check() error {
	if _u.mutation.LogCleared() && len(_u.mutation.LogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Logs.log"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *LogsUpdate) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LogsUpdate {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *LogsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(logs.Table, logs.Columns, sqlgraph.NewFieldSpec(logs.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Device(); ok {
		_spec.SetField(logs.FieldDevice, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(logs.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Referer(); ok {
		_spec.SetField(logs.FieldReferer, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(logs.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.LogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   logs.LogTable,
			Columns: []string{logs.LogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(url.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   logs.LogTable,
			Columns: []string{logs.LogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(url.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{logs.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// LogsUpdateOne is the builder for updating a single Logs entity.
type LogsUpdateOne struct {
	config
	fields    []string
	hooks     []Hook
	mutation  *LogsMutation
	modifiers []func(*sql.UpdateBuilder)
}

// SetDevice sets the "device" field.
func (_u *LogsUpdateOne) SetDevice(v string) *LogsUpdateOne {
	_u.mutation.SetDevice(v)
	return _u
}

// SetNillableDevice sets the "device" field if the given value is not nil.
func (_u *LogsUpdateOne) SetNillableDevice(v *string) *LogsUpdateOne {
	if v != nil {
		_u.SetDevice(*v)
	}
	return _u
}

// SetIP sets the "ip" field.
func (_u *LogsUpdateOne) SetIP(v string) *LogsUpdateOne {
	_u.mutation.SetIP(v)
	return _u
}

// SetNillableIP sets the "ip" field if the given value is not nil.
func (_u *LogsUpdateOne) SetNillableIP(v *string) *LogsUpdateOne {
	if v != nil {
		_u.SetIP(*v)
	}
	return _u
}

// SetReferer sets the "referer" field.
func (_u *LogsUpdateOne) SetReferer(v string) *LogsUpdateOne {
	_u.mutation.SetReferer(v)
	return _u
}

// SetNillableReferer sets the "referer" field if the given value is not nil.
func (_u *LogsUpdateOne) SetNillableReferer(v *string) *LogsUpdateOne {
	if v != nil {
		_u.SetReferer(*v)
	}
	return _u
}

// SetCreatedAt sets the "created_at" field.
func (_u *LogsUpdateOne) SetCreatedAt(v time.Time) *LogsUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_u *LogsUpdateOne) SetNillableCreatedAt(v *time.Time) *LogsUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetLogID sets the "log" edge to the Url entity by ID.
func (_u *LogsUpdateOne) SetLogID(id int) *LogsUpdateOne {
	_u.mutation.SetLogID(id)
	return _u
}

// SetLog sets the "log" edge to the Url entity.
func (_u *LogsUpdateOne) SetLog(v *Url) *LogsUpdateOne {
	return _u.SetLogID(v.ID)
}

// Mutation returns the LogsMutation object of the builder.
func (_u *LogsUpdateOne) Mutation() *LogsMutation {
	return _u.mutation
}

// ClearLog clears the "log" edge to the Url entity.
func (_u *LogsUpdateOne) ClearLog() *LogsUpdateOne {
	_u.mutation.ClearLog()
	return _u
}

// Where appends a list predicates to the LogsUpdate builder.
func (_u *LogsUpdateOne) Where(ps ...predicate.Logs) *LogsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *LogsUpdateOne) Select(field string, fields ...string) *LogsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Logs entity.
func (_u *LogsUpdateOne) Save(ctx context.Context) (*Logs, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *LogsUpdateOne) SaveX(ctx context.Context) *Logs {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *LogsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *LogsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *LogsUpdateOne) check() error {
	if _u.mutation.LogCleared() && len(_u.mutation.LogIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Logs.log"`)
	}
	return nil
}

// Modify adds a statement modifier for attaching custom logic to the UPDATE statement.
func (_u *LogsUpdateOne) Modify(modifiers ...func(u *sql.UpdateBuilder)) *LogsUpdateOne {
	_u.modifiers = append(_u.modifiers, modifiers...)
	return _u
}

func (_u *LogsUpdateOne) sqlSave(ctx context.Context) (_node *Logs, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(logs.Table, logs.Columns, sqlgraph.NewFieldSpec(logs.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Logs.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, logs.FieldID)
		for _, f := range fields {
			if !logs.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != logs.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Device(); ok {
		_spec.SetField(logs.FieldDevice, field.TypeString, value)
	}
	if value, ok := _u.mutation.IP(); ok {
		_spec.SetField(logs.FieldIP, field.TypeString, value)
	}
	if value, ok := _u.mutation.Referer(); ok {
		_spec.SetField(logs.FieldReferer, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(logs.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.LogCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   logs.LogTable,
			Columns: []string{logs.LogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(url.FieldID, field.TypeInt),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.LogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   logs.LogTable,
			Columns: []string{logs.LogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(url.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_spec.AddModifiers(_u.modifiers...)
	_node = &Logs{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{logs.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
