// Code generated by ent, DO NOT EDIT.

package ent

import (
	"2/ent/logs"
	"2/ent/url"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// LogsCreate is the builder for creating a Logs entity.
type LogsCreate struct {
	config
	mutation *LogsMutation
	hooks    []Hook
}

// SetDevice sets the "device" field.
func (_c *LogsCreate) SetDevice(v string) *LogsCreate {
	_c.mutation.SetDevice(v)
	return _c
}

// SetIP sets the "ip" field.
func (_c *LogsCreate) SetIP(v string) *LogsCreate {
	_c.mutation.SetIP(v)
	return _c
}

// SetReferer sets the "referer" field.
func (_c *LogsCreate) SetReferer(v string) *LogsCreate {
	_c.mutation.SetReferer(v)
	return _c
}

// SetLogID sets the "log" edge to the Url entity by ID.
func (_c *LogsCreate) SetLogID(id int) *LogsCreate {
	_c.mutation.SetLogID(id)
	return _c
}

// SetLog sets the "log" edge to the Url entity.
func (_c *LogsCreate) SetLog(v *Url) *LogsCreate {
	return _c.SetLogID(v.ID)
}

// Mutation returns the LogsMutation object of the builder.
func (_c *LogsCreate) Mutation() *LogsMutation {
	return _c.mutation
}

// Save creates the Logs in the database.
func (_c *LogsCreate) Save(ctx context.Context) (*Logs, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *LogsCreate) SaveX(ctx context.Context) *Logs {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LogsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LogsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *LogsCreate) check() error {
	if _, ok := _c.mutation.Device(); !ok {
		return &ValidationError{Name: "device", err: errors.New(`ent: missing required field "Logs.device"`)}
	}
	if _, ok := _c.mutation.IP(); !ok {
		return &ValidationError{Name: "ip", err: errors.New(`ent: missing required field "Logs.ip"`)}
	}
	if _, ok := _c.mutation.Referer(); !ok {
		return &ValidationError{Name: "referer", err: errors.New(`ent: missing required field "Logs.referer"`)}
	}
	if len(_c.mutation.LogIDs()) == 0 {
		return &ValidationError{Name: "log", err: errors.New(`ent: missing required edge "Logs.log"`)}
	}
	return nil
}

func (_c *LogsCreate) sqlSave(ctx context.Context) (*Logs, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *LogsCreate) createSpec() (*Logs, *sqlgraph.CreateSpec) {
	var (
		_node = &Logs{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(logs.Table, sqlgraph.NewFieldSpec(logs.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.Device(); ok {
		_spec.SetField(logs.FieldDevice, field.TypeString, value)
		_node.Device = value
	}
	if value, ok := _c.mutation.IP(); ok {
		_spec.SetField(logs.FieldIP, field.TypeString, value)
		_node.IP = value
	}
	if value, ok := _c.mutation.Referer(); ok {
		_spec.SetField(logs.FieldReferer, field.TypeString, value)
		_node.Referer = value
	}
	if nodes := _c.mutation.LogIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   logs.LogTable,
			Columns: []string{logs.LogColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(url.FieldID, field.TypeInt),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.url_log_url = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// LogsCreateBulk is the builder for creating many Logs entities in bulk.
type LogsCreateBulk struct {
	config
	err      error
	builders []*LogsCreate
}

// Save creates the Logs entities in the database.
func (_c *LogsCreateBulk) Save(ctx context.Context) ([]*Logs, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Logs, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*LogsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *LogsCreateBulk) SaveX(ctx context.Context) []*Logs {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *LogsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *LogsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
