// Code generated by ent, DO NOT EDIT.

package ent

import (
	"2/ent/url"
	"2/ent/user"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// Url is the model entity for the Url schema.
type Url struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// ShortCode holds the value of the "short_code" field.
	ShortCode string `json:"short_code,omitempty"`
	// LongURL holds the value of the "long_url" field.
	LongURL string `json:"long_url,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Alias holds the value of the "alias" field.
	Alias string `json:"alias,omitempty"`
	// IsEncrypted holds the value of the "is_encrypted" field.
	IsEncrypted bool `json:"is_encrypted,omitempty"`
	// Password holds the value of the "password" field.
	Password string `json:"-"`
	// ExpirationDate holds the value of the "expiration_date" field.
	ExpirationDate time.Time `json:"expiration_date,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UrlQuery when eager-loading is set.
	Edges        UrlEdges `json:"edges"`
	user_url     *int
	selectValues sql.SelectValues
}

// UrlEdges holds the relations/edges for other nodes in the graph.
type UrlEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// LogURL holds the value of the log_url edge.
	LogURL []*Logs `json:"log_url,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e UrlEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// LogURLOrErr returns the LogURL value or an error if the edge
// was not loaded in eager-loading.
func (e UrlEdges) LogURLOrErr() ([]*Logs, error) {
	if e.loadedTypes[1] {
		return e.LogURL, nil
	}
	return nil, &NotLoadedError{edge: "log_url"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Url) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case url.FieldIsEncrypted:
			values[i] = new(sql.NullBool)
		case url.FieldID:
			values[i] = new(sql.NullInt64)
		case url.FieldShortCode, url.FieldLongURL, url.FieldAlias, url.FieldPassword:
			values[i] = new(sql.NullString)
		case url.FieldCreatedAt, url.FieldExpirationDate:
			values[i] = new(sql.NullTime)
		case url.ForeignKeys[0]: // user_url
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Url fields.
func (_m *Url) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case url.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case url.FieldShortCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field short_code", values[i])
			} else if value.Valid {
				_m.ShortCode = value.String
			}
		case url.FieldLongURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field long_url", values[i])
			} else if value.Valid {
				_m.LongURL = value.String
			}
		case url.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case url.FieldAlias:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field alias", values[i])
			} else if value.Valid {
				_m.Alias = value.String
			}
		case url.FieldIsEncrypted:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_encrypted", values[i])
			} else if value.Valid {
				_m.IsEncrypted = value.Bool
			}
		case url.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = value.String
			}
		case url.FieldExpirationDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expiration_date", values[i])
			} else if value.Valid {
				_m.ExpirationDate = value.Time
			}
		case url.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for edge-field user_url", value)
			} else if value.Valid {
				_m.user_url = new(int)
				*_m.user_url = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Url.
// This includes values selected through modifiers, order, etc.
func (_m *Url) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the Url entity.
func (_m *Url) QueryUser() *UserQuery {
	return NewURLClient(_m.config).QueryUser(_m)
}

// QueryLogURL queries the "log_url" edge of the Url entity.
func (_m *Url) QueryLogURL() *LogsQuery {
	return NewURLClient(_m.config).QueryLogURL(_m)
}

// Update returns a builder for updating this Url.
// Note that you need to call Url.Unwrap() before calling this method if this Url
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Url) Update() *URLUpdateOne {
	return NewURLClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Url entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Url) Unwrap() *Url {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Url is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Url) String() string {
	var builder strings.Builder
	builder.WriteString("Url(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("short_code=")
	builder.WriteString(_m.ShortCode)
	builder.WriteString(", ")
	builder.WriteString("long_url=")
	builder.WriteString(_m.LongURL)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("alias=")
	builder.WriteString(_m.Alias)
	builder.WriteString(", ")
	builder.WriteString("is_encrypted=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsEncrypted))
	builder.WriteString(", ")
	builder.WriteString("password=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("expiration_date=")
	builder.WriteString(_m.ExpirationDate.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Urls is a parsable slice of Url.
type Urls []*Url
