// Code generated by ent, DO NOT EDIT.

package url

import (
	"api/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Url {
	return predicate.Url(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Url {
	return predicate.Url(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Url {
	return predicate.Url(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Url {
	return predicate.Url(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Url {
	return predicate.Url(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Url {
	return predicate.Url(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Url {
	return predicate.Url(sql.FieldLTE(FieldID, id))
}

// ShortCode applies equality check predicate on the "short_code" field. It's identical to ShortCodeEQ.
func ShortCode(v string) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldShortCode, v))
}

// LongURL applies equality check predicate on the "long_url" field. It's identical to LongURLEQ.
func LongURL(v string) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldLongURL, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldCreatedAt, v))
}

// Alias applies equality check predicate on the "alias" field. It's identical to AliasEQ.
func Alias(v string) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldAlias, v))
}

// IsEncrypted applies equality check predicate on the "is_encrypted" field. It's identical to IsEncryptedEQ.
func IsEncrypted(v bool) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldIsEncrypted, v))
}

// Password applies equality check predicate on the "password" field. It's identical to PasswordEQ.
func Password(v string) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldPassword, v))
}

// ExpirationDate applies equality check predicate on the "expiration_date" field. It's identical to ExpirationDateEQ.
func ExpirationDate(v time.Time) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldExpirationDate, v))
}

// ShortCodeEQ applies the EQ predicate on the "short_code" field.
func ShortCodeEQ(v string) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldShortCode, v))
}

// ShortCodeNEQ applies the NEQ predicate on the "short_code" field.
func ShortCodeNEQ(v string) predicate.Url {
	return predicate.Url(sql.FieldNEQ(FieldShortCode, v))
}

// ShortCodeIn applies the In predicate on the "short_code" field.
func ShortCodeIn(vs ...string) predicate.Url {
	return predicate.Url(sql.FieldIn(FieldShortCode, vs...))
}

// ShortCodeNotIn applies the NotIn predicate on the "short_code" field.
func ShortCodeNotIn(vs ...string) predicate.Url {
	return predicate.Url(sql.FieldNotIn(FieldShortCode, vs...))
}

// ShortCodeGT applies the GT predicate on the "short_code" field.
func ShortCodeGT(v string) predicate.Url {
	return predicate.Url(sql.FieldGT(FieldShortCode, v))
}

// ShortCodeGTE applies the GTE predicate on the "short_code" field.
func ShortCodeGTE(v string) predicate.Url {
	return predicate.Url(sql.FieldGTE(FieldShortCode, v))
}

// ShortCodeLT applies the LT predicate on the "short_code" field.
func ShortCodeLT(v string) predicate.Url {
	return predicate.Url(sql.FieldLT(FieldShortCode, v))
}

// ShortCodeLTE applies the LTE predicate on the "short_code" field.
func ShortCodeLTE(v string) predicate.Url {
	return predicate.Url(sql.FieldLTE(FieldShortCode, v))
}

// ShortCodeContains applies the Contains predicate on the "short_code" field.
func ShortCodeContains(v string) predicate.Url {
	return predicate.Url(sql.FieldContains(FieldShortCode, v))
}

// ShortCodeHasPrefix applies the HasPrefix predicate on the "short_code" field.
func ShortCodeHasPrefix(v string) predicate.Url {
	return predicate.Url(sql.FieldHasPrefix(FieldShortCode, v))
}

// ShortCodeHasSuffix applies the HasSuffix predicate on the "short_code" field.
func ShortCodeHasSuffix(v string) predicate.Url {
	return predicate.Url(sql.FieldHasSuffix(FieldShortCode, v))
}

// ShortCodeEqualFold applies the EqualFold predicate on the "short_code" field.
func ShortCodeEqualFold(v string) predicate.Url {
	return predicate.Url(sql.FieldEqualFold(FieldShortCode, v))
}

// ShortCodeContainsFold applies the ContainsFold predicate on the "short_code" field.
func ShortCodeContainsFold(v string) predicate.Url {
	return predicate.Url(sql.FieldContainsFold(FieldShortCode, v))
}

// LongURLEQ applies the EQ predicate on the "long_url" field.
func LongURLEQ(v string) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldLongURL, v))
}

// LongURLNEQ applies the NEQ predicate on the "long_url" field.
func LongURLNEQ(v string) predicate.Url {
	return predicate.Url(sql.FieldNEQ(FieldLongURL, v))
}

// LongURLIn applies the In predicate on the "long_url" field.
func LongURLIn(vs ...string) predicate.Url {
	return predicate.Url(sql.FieldIn(FieldLongURL, vs...))
}

// LongURLNotIn applies the NotIn predicate on the "long_url" field.
func LongURLNotIn(vs ...string) predicate.Url {
	return predicate.Url(sql.FieldNotIn(FieldLongURL, vs...))
}

// LongURLGT applies the GT predicate on the "long_url" field.
func LongURLGT(v string) predicate.Url {
	return predicate.Url(sql.FieldGT(FieldLongURL, v))
}

// LongURLGTE applies the GTE predicate on the "long_url" field.
func LongURLGTE(v string) predicate.Url {
	return predicate.Url(sql.FieldGTE(FieldLongURL, v))
}

// LongURLLT applies the LT predicate on the "long_url" field.
func LongURLLT(v string) predicate.Url {
	return predicate.Url(sql.FieldLT(FieldLongURL, v))
}

// LongURLLTE applies the LTE predicate on the "long_url" field.
func LongURLLTE(v string) predicate.Url {
	return predicate.Url(sql.FieldLTE(FieldLongURL, v))
}

// LongURLContains applies the Contains predicate on the "long_url" field.
func LongURLContains(v string) predicate.Url {
	return predicate.Url(sql.FieldContains(FieldLongURL, v))
}

// LongURLHasPrefix applies the HasPrefix predicate on the "long_url" field.
func LongURLHasPrefix(v string) predicate.Url {
	return predicate.Url(sql.FieldHasPrefix(FieldLongURL, v))
}

// LongURLHasSuffix applies the HasSuffix predicate on the "long_url" field.
func LongURLHasSuffix(v string) predicate.Url {
	return predicate.Url(sql.FieldHasSuffix(FieldLongURL, v))
}

// LongURLEqualFold applies the EqualFold predicate on the "long_url" field.
func LongURLEqualFold(v string) predicate.Url {
	return predicate.Url(sql.FieldEqualFold(FieldLongURL, v))
}

// LongURLContainsFold applies the ContainsFold predicate on the "long_url" field.
func LongURLContainsFold(v string) predicate.Url {
	return predicate.Url(sql.FieldContainsFold(FieldLongURL, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Url {
	return predicate.Url(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Url {
	return predicate.Url(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Url {
	return predicate.Url(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Url {
	return predicate.Url(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Url {
	return predicate.Url(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Url {
	return predicate.Url(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Url {
	return predicate.Url(sql.FieldLTE(FieldCreatedAt, v))
}

// AliasEQ applies the EQ predicate on the "alias" field.
func AliasEQ(v string) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldAlias, v))
}

// AliasNEQ applies the NEQ predicate on the "alias" field.
func AliasNEQ(v string) predicate.Url {
	return predicate.Url(sql.FieldNEQ(FieldAlias, v))
}

// AliasIn applies the In predicate on the "alias" field.
func AliasIn(vs ...string) predicate.Url {
	return predicate.Url(sql.FieldIn(FieldAlias, vs...))
}

// AliasNotIn applies the NotIn predicate on the "alias" field.
func AliasNotIn(vs ...string) predicate.Url {
	return predicate.Url(sql.FieldNotIn(FieldAlias, vs...))
}

// AliasGT applies the GT predicate on the "alias" field.
func AliasGT(v string) predicate.Url {
	return predicate.Url(sql.FieldGT(FieldAlias, v))
}

// AliasGTE applies the GTE predicate on the "alias" field.
func AliasGTE(v string) predicate.Url {
	return predicate.Url(sql.FieldGTE(FieldAlias, v))
}

// AliasLT applies the LT predicate on the "alias" field.
func AliasLT(v string) predicate.Url {
	return predicate.Url(sql.FieldLT(FieldAlias, v))
}

// AliasLTE applies the LTE predicate on the "alias" field.
func AliasLTE(v string) predicate.Url {
	return predicate.Url(sql.FieldLTE(FieldAlias, v))
}

// AliasContains applies the Contains predicate on the "alias" field.
func AliasContains(v string) predicate.Url {
	return predicate.Url(sql.FieldContains(FieldAlias, v))
}

// AliasHasPrefix applies the HasPrefix predicate on the "alias" field.
func AliasHasPrefix(v string) predicate.Url {
	return predicate.Url(sql.FieldHasPrefix(FieldAlias, v))
}

// AliasHasSuffix applies the HasSuffix predicate on the "alias" field.
func AliasHasSuffix(v string) predicate.Url {
	return predicate.Url(sql.FieldHasSuffix(FieldAlias, v))
}

// AliasIsNil applies the IsNil predicate on the "alias" field.
func AliasIsNil() predicate.Url {
	return predicate.Url(sql.FieldIsNull(FieldAlias))
}

// AliasNotNil applies the NotNil predicate on the "alias" field.
func AliasNotNil() predicate.Url {
	return predicate.Url(sql.FieldNotNull(FieldAlias))
}

// AliasEqualFold applies the EqualFold predicate on the "alias" field.
func AliasEqualFold(v string) predicate.Url {
	return predicate.Url(sql.FieldEqualFold(FieldAlias, v))
}

// AliasContainsFold applies the ContainsFold predicate on the "alias" field.
func AliasContainsFold(v string) predicate.Url {
	return predicate.Url(sql.FieldContainsFold(FieldAlias, v))
}

// IsEncryptedEQ applies the EQ predicate on the "is_encrypted" field.
func IsEncryptedEQ(v bool) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldIsEncrypted, v))
}

// IsEncryptedNEQ applies the NEQ predicate on the "is_encrypted" field.
func IsEncryptedNEQ(v bool) predicate.Url {
	return predicate.Url(sql.FieldNEQ(FieldIsEncrypted, v))
}

// IsEncryptedIsNil applies the IsNil predicate on the "is_encrypted" field.
func IsEncryptedIsNil() predicate.Url {
	return predicate.Url(sql.FieldIsNull(FieldIsEncrypted))
}

// IsEncryptedNotNil applies the NotNil predicate on the "is_encrypted" field.
func IsEncryptedNotNil() predicate.Url {
	return predicate.Url(sql.FieldNotNull(FieldIsEncrypted))
}

// PasswordEQ applies the EQ predicate on the "password" field.
func PasswordEQ(v string) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldPassword, v))
}

// PasswordNEQ applies the NEQ predicate on the "password" field.
func PasswordNEQ(v string) predicate.Url {
	return predicate.Url(sql.FieldNEQ(FieldPassword, v))
}

// PasswordIn applies the In predicate on the "password" field.
func PasswordIn(vs ...string) predicate.Url {
	return predicate.Url(sql.FieldIn(FieldPassword, vs...))
}

// PasswordNotIn applies the NotIn predicate on the "password" field.
func PasswordNotIn(vs ...string) predicate.Url {
	return predicate.Url(sql.FieldNotIn(FieldPassword, vs...))
}

// PasswordGT applies the GT predicate on the "password" field.
func PasswordGT(v string) predicate.Url {
	return predicate.Url(sql.FieldGT(FieldPassword, v))
}

// PasswordGTE applies the GTE predicate on the "password" field.
func PasswordGTE(v string) predicate.Url {
	return predicate.Url(sql.FieldGTE(FieldPassword, v))
}

// PasswordLT applies the LT predicate on the "password" field.
func PasswordLT(v string) predicate.Url {
	return predicate.Url(sql.FieldLT(FieldPassword, v))
}

// PasswordLTE applies the LTE predicate on the "password" field.
func PasswordLTE(v string) predicate.Url {
	return predicate.Url(sql.FieldLTE(FieldPassword, v))
}

// PasswordContains applies the Contains predicate on the "password" field.
func PasswordContains(v string) predicate.Url {
	return predicate.Url(sql.FieldContains(FieldPassword, v))
}

// PasswordHasPrefix applies the HasPrefix predicate on the "password" field.
func PasswordHasPrefix(v string) predicate.Url {
	return predicate.Url(sql.FieldHasPrefix(FieldPassword, v))
}

// PasswordHasSuffix applies the HasSuffix predicate on the "password" field.
func PasswordHasSuffix(v string) predicate.Url {
	return predicate.Url(sql.FieldHasSuffix(FieldPassword, v))
}

// PasswordIsNil applies the IsNil predicate on the "password" field.
func PasswordIsNil() predicate.Url {
	return predicate.Url(sql.FieldIsNull(FieldPassword))
}

// PasswordNotNil applies the NotNil predicate on the "password" field.
func PasswordNotNil() predicate.Url {
	return predicate.Url(sql.FieldNotNull(FieldPassword))
}

// PasswordEqualFold applies the EqualFold predicate on the "password" field.
func PasswordEqualFold(v string) predicate.Url {
	return predicate.Url(sql.FieldEqualFold(FieldPassword, v))
}

// PasswordContainsFold applies the ContainsFold predicate on the "password" field.
func PasswordContainsFold(v string) predicate.Url {
	return predicate.Url(sql.FieldContainsFold(FieldPassword, v))
}

// ExpirationDateEQ applies the EQ predicate on the "expiration_date" field.
func ExpirationDateEQ(v time.Time) predicate.Url {
	return predicate.Url(sql.FieldEQ(FieldExpirationDate, v))
}

// ExpirationDateNEQ applies the NEQ predicate on the "expiration_date" field.
func ExpirationDateNEQ(v time.Time) predicate.Url {
	return predicate.Url(sql.FieldNEQ(FieldExpirationDate, v))
}

// ExpirationDateIn applies the In predicate on the "expiration_date" field.
func ExpirationDateIn(vs ...time.Time) predicate.Url {
	return predicate.Url(sql.FieldIn(FieldExpirationDate, vs...))
}

// ExpirationDateNotIn applies the NotIn predicate on the "expiration_date" field.
func ExpirationDateNotIn(vs ...time.Time) predicate.Url {
	return predicate.Url(sql.FieldNotIn(FieldExpirationDate, vs...))
}

// ExpirationDateGT applies the GT predicate on the "expiration_date" field.
func ExpirationDateGT(v time.Time) predicate.Url {
	return predicate.Url(sql.FieldGT(FieldExpirationDate, v))
}

// ExpirationDateGTE applies the GTE predicate on the "expiration_date" field.
func ExpirationDateGTE(v time.Time) predicate.Url {
	return predicate.Url(sql.FieldGTE(FieldExpirationDate, v))
}

// ExpirationDateLT applies the LT predicate on the "expiration_date" field.
func ExpirationDateLT(v time.Time) predicate.Url {
	return predicate.Url(sql.FieldLT(FieldExpirationDate, v))
}

// ExpirationDateLTE applies the LTE predicate on the "expiration_date" field.
func ExpirationDateLTE(v time.Time) predicate.Url {
	return predicate.Url(sql.FieldLTE(FieldExpirationDate, v))
}

// ExpirationDateIsNil applies the IsNil predicate on the "expiration_date" field.
func ExpirationDateIsNil() predicate.Url {
	return predicate.Url(sql.FieldIsNull(FieldExpirationDate))
}

// ExpirationDateNotNil applies the NotNil predicate on the "expiration_date" field.
func ExpirationDateNotNil() predicate.Url {
	return predicate.Url(sql.FieldNotNull(FieldExpirationDate))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.Url {
	return predicate.Url(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.Url {
	return predicate.Url(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasLogURL applies the HasEdge predicate on the "log_url" edge.
func HasLogURL() predicate.Url {
	return predicate.Url(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, LogURLTable, LogURLColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasLogURLWith applies the HasEdge predicate on the "log_url" edge with a given conditions (other predicates).
func HasLogURLWith(preds ...predicate.Logs) predicate.Url {
	return predicate.Url(func(s *sql.Selector) {
		step := newLogURLStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Url) predicate.Url {
	return predicate.Url(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Url) predicate.Url {
	return predicate.Url(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Url) predicate.Url {
	return predicate.Url(sql.NotPredicates(p))
}
