// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Logs is the predicate function for logs builders.
type Logs func(*sql.Selector)

// Post is the predicate function for post builders.
type Post func(*sql.Selector)

// Url is the predicate function for url builders.
type Url func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
