swagger: "2.0"
info: {}
paths: {}
definitions:
  dto.CreateUrlRequest:
    title: CreateUrlRequest
    type: object
    properties:
      long_url:
        type: string
  dto.LoginRequest:
    title: LoginRequest
    type: object
    properties:
      email:
        type: string
      password:
        type: string
  dto.LoginResponse:
    title: LoginResponse
    type: object
    properties:
      token:
        type: string
  dto.RegisterRequest:
    title: RegisterRequest
    type: object
    properties:
      email:
        type: string
      name:
        type: string
      password:
        type: string
  dto.UpdateUrlRequest:
    title: UpdateUrlRequest
    type: object
    properties:
      id:
        type: integer
        format: int64
      long_url:
        type: string
  dto.UrlResponse:
    title: UrlResponse
    type: object
    properties:
      created_at:
        type: string
      id:
        type: integer
        format: int64
      long_url:
        type: string
      short_code:
        type: string
  dto.UserResponse:
    title: UserResponse
    type: object
    properties:
      email:
        type: string
      name:
        type: string
