// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// LogsColumns holds the columns for the "logs" table.
	LogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "device", Type: field.TypeString},
		{Name: "ip", Type: field.TypeString},
		{Name: "referer", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "url_log_url", Type: field.TypeInt},
	}
	// LogsTable holds the schema information for the "logs" table.
	LogsTable = &schema.Table{
		Name:       "logs",
		Columns:    LogsColumns,
		PrimaryKey: []*schema.Column{LogsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "logs_urls_log_url",
				Columns:    []*schema.Column{LogsColumns[5]},
				RefColumns: []*schema.Column{UrlsColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// PostsColumns holds the columns for the "posts" table.
	PostsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "post_title", Type: field.TypeString, Size: 255},
		{Name: "post_content", Type: field.TypeString, Nullable: true, Size: 2147483647},
	}
	// PostsTable holds the schema information for the "posts" table.
	PostsTable = &schema.Table{
		Name:       "posts",
		Columns:    PostsColumns,
		PrimaryKey: []*schema.Column{PostsColumns[0]},
	}
	// UrlsColumns holds the columns for the "urls" table.
	UrlsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "short_code", Type: field.TypeString, Unique: true, Size: 255},
		{Name: "long_url", Type: field.TypeString, Size: 2147483647},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "alias", Type: field.TypeString, Nullable: true},
		{Name: "is_encrypted", Type: field.TypeBool, Nullable: true, Default: false},
		{Name: "password", Type: field.TypeString, Nullable: true},
		{Name: "expiration_date", Type: field.TypeTime, Nullable: true},
		{Name: "user_url", Type: field.TypeInt},
	}
	// UrlsTable holds the schema information for the "urls" table.
	UrlsTable = &schema.Table{
		Name:       "urls",
		Columns:    UrlsColumns,
		PrimaryKey: []*schema.Column{UrlsColumns[0]},
		ForeignKeys: []*schema.ForeignKey{
			{
				Symbol:     "urls_users_url",
				Columns:    []*schema.Column{UrlsColumns[8]},
				RefColumns: []*schema.Column{UsersColumns[0]},
				OnDelete:   schema.NoAction,
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "ad", Type: field.TypeString, Size: 100},
		{Name: "email", Type: field.TypeString, Unique: true},
		{Name: "password", Type: field.TypeString},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		LogsTable,
		PostsTable,
		UrlsTable,
		UsersTable,
	}
)

func init() {
	LogsTable.ForeignKeys[0].RefTable = UrlsTable
	UrlsTable.ForeignKeys[0].RefTable = UsersTable
}
