// Code generated by ent, DO NOT EDIT.

package logs

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the logs type in the database.
	Label = "logs"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldDevice holds the string denoting the device field in the database.
	FieldDevice = "device"
	// FieldIP holds the string denoting the ip field in the database.
	FieldIP = "ip"
	// FieldReferer holds the string denoting the referer field in the database.
	FieldReferer = "referer"
	// EdgeLog holds the string denoting the log edge name in mutations.
	EdgeLog = "log"
	// Table holds the table name of the logs in the database.
	Table = "logs"
	// LogTable is the table that holds the log relation/edge.
	LogTable = "logs"
	// LogInverseTable is the table name for the Url entity.
	// It exists in this package in order to avoid circular dependency with the "url" package.
	LogInverseTable = "urls"
	// LogColumn is the table column denoting the log relation/edge.
	LogColumn = "url_log_url"
)

// Columns holds all SQL columns for logs fields.
var Columns = []string{
	FieldID,
	FieldDevice,
	FieldIP,
	FieldReferer,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the "logs"
// table and are not defined as standalone fields in the schema.
var ForeignKeys = []string{
	"url_log_url",
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	for i := range ForeignKeys {
		if column == ForeignKeys[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Logs queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDevice orders the results by the device field.
func ByDevice(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDevice, opts...).ToFunc()
}

// ByIP orders the results by the ip field.
func ByIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIP, opts...).ToFunc()
}

// ByReferer orders the results by the referer field.
func ByReferer(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReferer, opts...).ToFunc()
}

// ByLogField orders the results by log field.
func ByLogField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newLogStep(), sql.OrderByField(field, opts...))
	}
}
func newLogStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(LogInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, LogTable, LogColumn),
	)
}
