// Code generated by ent, DO NOT EDIT.

package setting

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the setting type in the database.
	Label = "setting"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSettingsKey holds the string denoting the settings_key field in the database.
	FieldSettingsKey = "settings_key"
	// FieldSettingContent holds the string denoting the setting_content field in the database.
	FieldSettingContent = "setting_content"
	// Table holds the table name of the setting in the database.
	Table = "settings"
)

// Columns holds all SQL columns for setting fields.
var Columns = []string{
	FieldID,
	FieldSettingsKey,
	FieldSettingContent,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the Setting queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySettingsKey orders the results by the settings_key field.
func BySettingsKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettingsKey, opts...).ToFunc()
}

// BySettingContent orders the results by the setting_content field.
func BySettingContent(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSettingContent, opts...).ToFunc()
}
