// Code generated by ent, DO NOT EDIT.

package setting

import (
	"api/ent/predicate"

	"entgo.io/ent/dialect/sql"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Setting {
	return predicate.Setting(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Setting {
	return predicate.Setting(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Setting {
	return predicate.Setting(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Setting {
	return predicate.Setting(sql.FieldLTE(FieldID, id))
}

// SettingsKey applies equality check predicate on the "settings_key" field. It's identical to SettingsKeyEQ.
func SettingsKey(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldSettingsKey, v))
}

// SettingContent applies equality check predicate on the "setting_content" field. It's identical to SettingContentEQ.
func SettingContent(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldSettingContent, v))
}

// SettingsKeyEQ applies the EQ predicate on the "settings_key" field.
func SettingsKeyEQ(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldSettingsKey, v))
}

// SettingsKeyNEQ applies the NEQ predicate on the "settings_key" field.
func SettingsKeyNEQ(v string) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldSettingsKey, v))
}

// SettingsKeyIn applies the In predicate on the "settings_key" field.
func SettingsKeyIn(vs ...string) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldSettingsKey, vs...))
}

// SettingsKeyNotIn applies the NotIn predicate on the "settings_key" field.
func SettingsKeyNotIn(vs ...string) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldSettingsKey, vs...))
}

// SettingsKeyGT applies the GT predicate on the "settings_key" field.
func SettingsKeyGT(v string) predicate.Setting {
	return predicate.Setting(sql.FieldGT(FieldSettingsKey, v))
}

// SettingsKeyGTE applies the GTE predicate on the "settings_key" field.
func SettingsKeyGTE(v string) predicate.Setting {
	return predicate.Setting(sql.FieldGTE(FieldSettingsKey, v))
}

// SettingsKeyLT applies the LT predicate on the "settings_key" field.
func SettingsKeyLT(v string) predicate.Setting {
	return predicate.Setting(sql.FieldLT(FieldSettingsKey, v))
}

// SettingsKeyLTE applies the LTE predicate on the "settings_key" field.
func SettingsKeyLTE(v string) predicate.Setting {
	return predicate.Setting(sql.FieldLTE(FieldSettingsKey, v))
}

// SettingsKeyContains applies the Contains predicate on the "settings_key" field.
func SettingsKeyContains(v string) predicate.Setting {
	return predicate.Setting(sql.FieldContains(FieldSettingsKey, v))
}

// SettingsKeyHasPrefix applies the HasPrefix predicate on the "settings_key" field.
func SettingsKeyHasPrefix(v string) predicate.Setting {
	return predicate.Setting(sql.FieldHasPrefix(FieldSettingsKey, v))
}

// SettingsKeyHasSuffix applies the HasSuffix predicate on the "settings_key" field.
func SettingsKeyHasSuffix(v string) predicate.Setting {
	return predicate.Setting(sql.FieldHasSuffix(FieldSettingsKey, v))
}

// SettingsKeyEqualFold applies the EqualFold predicate on the "settings_key" field.
func SettingsKeyEqualFold(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEqualFold(FieldSettingsKey, v))
}

// SettingsKeyContainsFold applies the ContainsFold predicate on the "settings_key" field.
func SettingsKeyContainsFold(v string) predicate.Setting {
	return predicate.Setting(sql.FieldContainsFold(FieldSettingsKey, v))
}

// SettingContentEQ applies the EQ predicate on the "setting_content" field.
func SettingContentEQ(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEQ(FieldSettingContent, v))
}

// SettingContentNEQ applies the NEQ predicate on the "setting_content" field.
func SettingContentNEQ(v string) predicate.Setting {
	return predicate.Setting(sql.FieldNEQ(FieldSettingContent, v))
}

// SettingContentIn applies the In predicate on the "setting_content" field.
func SettingContentIn(vs ...string) predicate.Setting {
	return predicate.Setting(sql.FieldIn(FieldSettingContent, vs...))
}

// SettingContentNotIn applies the NotIn predicate on the "setting_content" field.
func SettingContentNotIn(vs ...string) predicate.Setting {
	return predicate.Setting(sql.FieldNotIn(FieldSettingContent, vs...))
}

// SettingContentGT applies the GT predicate on the "setting_content" field.
func SettingContentGT(v string) predicate.Setting {
	return predicate.Setting(sql.FieldGT(FieldSettingContent, v))
}

// SettingContentGTE applies the GTE predicate on the "setting_content" field.
func SettingContentGTE(v string) predicate.Setting {
	return predicate.Setting(sql.FieldGTE(FieldSettingContent, v))
}

// SettingContentLT applies the LT predicate on the "setting_content" field.
func SettingContentLT(v string) predicate.Setting {
	return predicate.Setting(sql.FieldLT(FieldSettingContent, v))
}

// SettingContentLTE applies the LTE predicate on the "setting_content" field.
func SettingContentLTE(v string) predicate.Setting {
	return predicate.Setting(sql.FieldLTE(FieldSettingContent, v))
}

// SettingContentContains applies the Contains predicate on the "setting_content" field.
func SettingContentContains(v string) predicate.Setting {
	return predicate.Setting(sql.FieldContains(FieldSettingContent, v))
}

// SettingContentHasPrefix applies the HasPrefix predicate on the "setting_content" field.
func SettingContentHasPrefix(v string) predicate.Setting {
	return predicate.Setting(sql.FieldHasPrefix(FieldSettingContent, v))
}

// SettingContentHasSuffix applies the HasSuffix predicate on the "setting_content" field.
func SettingContentHasSuffix(v string) predicate.Setting {
	return predicate.Setting(sql.FieldHasSuffix(FieldSettingContent, v))
}

// SettingContentEqualFold applies the EqualFold predicate on the "setting_content" field.
func SettingContentEqualFold(v string) predicate.Setting {
	return predicate.Setting(sql.FieldEqualFold(FieldSettingContent, v))
}

// SettingContentContainsFold applies the ContainsFold predicate on the "setting_content" field.
func SettingContentContainsFold(v string) predicate.Setting {
	return predicate.Setting(sql.FieldContainsFold(FieldSettingContent, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Setting) predicate.Setting {
	return predicate.Setting(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Setting) predicate.Setting {
	return predicate.Setting(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Setting) predicate.Setting {
	return predicate.Setting(sql.NotPredicates(p))
}
