appname = client_
httpport = 8081
runmode = dev
api_url=http://localhost:8080/v1/
sessionon = true
sessionname = urlshorter_
sessionprovider = file
sessionproviderconfig = "./tmp"
defaultlang="en"
baseurl="http://localhost:8081"
