appname = client_
runmode = dev
sessionon = true
sessionname = urlshorter_
sessionprovider = file
sessionproviderconfig = "./tmp"
defaultlang="en"
baseurl="http://localhost:8081"
httpport = ${PORT||8080}
StaticDir = static:static
